name: CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Xcode environment
      - name: Set Xcode Version
        run: |
          sudo xcode-select -switch /Applications/Xcode_15.3.app

      # Publish to CocoaPods
      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          if [ -f "WhiteboxCryptography.podspec" ]; then
            pod trunk push WhiteboxCryptography.podspec --verbose --allow-warnings
          else
            echo "Error: WhiteboxCryptography.podspec not found!" && exit 1
          fi
