name: CI

on:
  push:
    branches:
      - develop
    tags:
      - "*"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Xcode (manually select the correct version)
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcode-select --print-path
          xcodebuild -version

      # Install all simulators (iPhone, iPad, Apple Watch, Apple TV, and xrOS)
      - name: Install all simulators
        run: |
          # List available runtimes to see if the ones you need are installed
          xcrun simctl list runtimes

          # Install iOS, iPadOS, watchOS, tvOS, and xrOS simulators
          # Make sure Xcode is selected
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

          # Run first launch to initialize Xcode
          xcodebuild -runFirstLaunch

          # Install simulators (adjust versions based on your needs)
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          xcodebuild -installRunTime -runtime "com.apple.CoreSimulator.SimRuntime.iOS-15-5"
          xcodebuild -installRunTime -runtime "com.apple.CoreSimulator.SimRuntime.tvOS-15-5"
          xcodebuild -installRunTime -runtime "com.apple.CoreSimulator.SimRuntime.watchOS-8-5"
          xcodebuild -installRunTime -runtime "com.apple.CoreSimulator.SimRuntime.iPadOS-15-5"
          xcodebuild -installRunTime -runtime "com.apple.CoreSimulator.SimRuntime.xrOS-1-3"

      # Publish to CocoaPods
      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push WhiteBoxCryptographySDK.podspec --verbose --allow-warnings

      # Upload to Carthage
      - name: Upload to Carthage
        run: |
          carthage build --use-xcframeworks --archive

      # Add more steps as necessary for tests or other tasks
