name: CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Publish to CocoaPods
      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push WhiteboxCryptography.podspec --verbose --allow-warnings

      # Upload to Carthage
      - name: Upload to Carthage
        run: |
          carthage build --use-xcframeworks --archive

      # Add more steps as necessary for tests or other tasks
